# Generated by Django 5.2.11 on 2026-02-18 16:18

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("artists", "0001_initial"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
        ("wagtaildocs", "0014_alter_document_file_size"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Home Page",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="EPKPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Es: 'Red Moon — Press Kit 2026'",
                        max_length=200,
                        verbose_name="Titolo EPK",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descrizione"),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Se True, non richiede autenticazione per il download.",
                        verbose_name="Pubblicamente accessibile",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="epk_packages",
                        to="artists.artistpage",
                        verbose_name="Artista",
                    ),
                ),
                (
                    "biography_pdf",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtaildocs.document",
                        verbose_name="Biografia PDF",
                    ),
                ),
                (
                    "logo_vector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtaildocs.document",
                        verbose_name="Logo vettoriale (SVG/AI)",
                    ),
                ),
                (
                    "press_photo_hires",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Foto stampa alta risoluzione",
                    ),
                ),
                (
                    "technical_rider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtaildocs.document",
                        verbose_name="Rider tecnico (PDF)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kit Stampa (EPK)",
                "verbose_name_plural": "Kit Stampa (EPK)",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="MagixSiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        default="Magix Promotion",
                        max_length=200,
                        verbose_name="Ragione sociale",
                    ),
                ),
                (
                    "vat_number",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Partita IVA"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        default="+39 335 523 0855",
                        max_length=30,
                        verbose_name="Telefono",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="info@magixpromotion.it",
                        max_length=254,
                        verbose_name="Email principale",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        default="Via dello Scabiolo",
                        max_length=300,
                        verbose_name="Indirizzo",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        default="Novi Ligure", max_length=100, verbose_name="Citta"
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        default="AL", max_length=10, verbose_name="Provincia"
                    ),
                ),
                (
                    "zip_code",
                    models.CharField(
                        default="15067", max_length=20, verbose_name="CAP"
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        default="IT", max_length=2, verbose_name="Paese"
                    ),
                ),
                (
                    "hq_latitude",
                    models.DecimalField(
                        decimal_places=6,
                        default=44.7631,
                        max_digits=9,
                        verbose_name="Latitudine sede",
                    ),
                ),
                (
                    "hq_longitude",
                    models.DecimalField(
                        decimal_places=6,
                        default=8.7873,
                        max_digits=9,
                        verbose_name="Longitudine sede",
                    ),
                ),
                ("facebook_url", models.URLField(blank=True, verbose_name="Facebook")),
                (
                    "instagram_url",
                    models.URLField(blank=True, verbose_name="Instagram"),
                ),
                ("youtube_url", models.URLField(blank=True, verbose_name="YouTube")),
                ("spotify_url", models.URLField(blank=True, verbose_name="Spotify")),
                (
                    "gemini_api_key",
                    models.CharField(
                        blank=True,
                        help_text="Chiave API Google Gemini per traduzioni automatiche e BandFinder.",
                        max_length=200,
                        verbose_name="Gemini API Key",
                    ),
                ),
                (
                    "nominatim_user_agent",
                    models.CharField(
                        default="magixpromotion",
                        help_text="User agent per le richieste a Nominatim/OSM.",
                        max_length=100,
                        verbose_name="Nominatim User-Agent",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Impostazioni Magix Promotion",
            },
        ),
    ]
