# Generated by Django 5.2.11 on 2026-02-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_groups_and_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='magixsitesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, help_text='Measurement ID di Google Analytics (es: G-XXXXXXXXXX). Vuoto = disabilitato.', max_length=50, verbose_name='Google Analytics ID'),
        ),
        migrations.AddField(
            model_name='magixsitesettings',
            name='matomo_site_id',
            field=models.CharField(blank=True, help_text='ID del sito configurato su Matomo. Vuoto = usa valore da settings.', max_length=20, verbose_name='Matomo Site ID'),
        ),
        migrations.AddField(
            model_name='magixsitesettings',
            name='matomo_url',
            field=models.CharField(blank=True, help_text='URL base del server Matomo (es: //piwik.gpsbooking.com/). Vuoto = usa valore da settings.', max_length=300, verbose_name='Matomo URL'),
        ),
    ]
