# Generated by Django 5.2.12 on 2026-03-06 20:06

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_analytics_fields'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressAreaPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, help_text='Breve sottotitolo visualizzato sotto il titolo.', max_length=300, verbose_name='Sottotitolo')),
                ('intro_text', wagtail.fields.RichTextField(blank=True, help_text='Presentazione di Magix Promotion per la press area.', verbose_name='Testo introduttivo')),
                ('company_epk', models.ForeignKey(blank=True, help_text='Press kit di Magix Promotion (mostrato in evidenza).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.epkpackage', verbose_name='EPK Aziendale')),
            ],
            options={
                'verbose_name': 'Press Area',
                'verbose_name_plural': 'Press Area',
            },
            bases=('wagtailcore.page',),
        ),
    ]
