# Generated by Django 5.2.12 on 2026-03-06 20:51

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pressareapage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressareapage',
            name='intro_text',
            field=wagtail.fields.StreamField([('heading', 2), ('richtext', 3), ('image', 6), ('gallery', 12), ('cta', 17)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], 'help_text': 'Mai H1 — riservato al titolo pagina.'}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'h3', 'h4']}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5)]], {'icon': 'image', 'label': 'Immagine'}), 7: ('wagtail.blocks.CharBlock', (), {'default': 'Gallery', 'required': False}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('grid', 'Griglia (3 colonne)'), ('carousel', 'Carosello'), ('masonry', 'Masonry')]}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Crediti fotografo.', 'max_length': 100, 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('credit', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {}), 12: ('wagtail.blocks.StructBlock', [[('heading', 7), ('layout', 8), ('images', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'Testo del bottone.', 'max_length': 100}), 14: ('wagtail.blocks.URLBlock', (), {'help_text': 'Link esterno.', 'required': False}), 15: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Oppure link a pagina interna.', 'required': False}), 16: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primario (pieno)'), ('secondary', 'Secondario (outline)'), ('accent', 'Accent (gradient)')]}), 17: ('wagtail.blocks.StructBlock', [[('text', 13), ('url', 14), ('page', 15), ('style', 16)]], {})}, help_text='Contenuto della press area con blocchi liberi.', verbose_name='Contenuto'),
        ),
    ]
