# Generated by Django 5.2.12 on 2026-03-06 20:51

import json
import uuid

import wagtail.fields
from django.db import migrations


def convert_richtext_to_streamfield(apps, schema_editor):
    """Converte l'intro_text da RichTextField (HTML) a StreamField JSON.

    Wrappa l'HTML esistente in un singolo blocco richtext, oppure
    imposta [] se il campo è vuoto.
    """
    PressAreaPage = apps.get_model("core", "PressAreaPage")
    for page in PressAreaPage.objects.all():
        old_value = page.intro_text or ""
        if old_value and not old_value.startswith("["):
            # È HTML puro dal vecchio RichTextField → wrappalo
            sf_json = json.dumps([
                {
                    "type": "richtext",
                    "value": old_value,
                    "id": str(uuid.uuid4())[:8],
                }
            ])
        elif not old_value:
            sf_json = "[]"
        else:
            # Già JSON (non dovrebbe succedere, ma per sicurezza)
            sf_json = old_value
        # Scrivi direttamente tramite SQL per evitare validazione campo
        PressAreaPage.objects.filter(pk=page.pk).update(intro_text=sf_json)


def noop(apps, schema_editor):
    """Reverse: noop — non possiamo tornare da StreamField a RichText."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pressareapage'),
    ]

    operations = [
        # 1. Prima converti i dati esistenti da HTML a JSON
        migrations.RunPython(convert_richtext_to_streamfield, noop),
        # 2. Poi altera il campo
        migrations.AlterField(
            model_name='pressareapage',
            name='intro_text',
            field=wagtail.fields.StreamField([('heading', 2), ('richtext', 3), ('image', 6), ('gallery', 12), ('cta', 17)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], 'help_text': 'Mai H1 — riservato al titolo pagina.'}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'h3', 'h4']}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5)]], {'icon': 'image', 'label': 'Immagine'}), 7: ('wagtail.blocks.CharBlock', (), {'default': 'Gallery', 'required': False}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('grid', 'Griglia (3 colonne)'), ('carousel', 'Carosello'), ('masonry', 'Masonry')]}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Crediti fotografo.', 'max_length': 100, 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('credit', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {}), 12: ('wagtail.blocks.StructBlock', [[('heading', 7), ('layout', 8), ('images', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'Testo del bottone.', 'max_length': 100}), 14: ('wagtail.blocks.URLBlock', (), {'help_text': 'Link esterno.', 'required': False}), 15: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Oppure link a pagina interna.', 'required': False}), 16: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primario (pieno)'), ('secondary', 'Secondario (outline)'), ('accent', 'Accent (gradient)')]}), 17: ('wagtail.blocks.StructBlock', [[('text', 13), ('url', 14), ('page', 15), ('style', 16)]], {})}, help_text='Contenuto della press area con blocchi liberi.', verbose_name='Contenuto'),
        ),
    ]
