# Generated by Django 5.2.12 on 2026-03-06 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_convert_pressarea_to_streamfield'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='epkpackage',
            name='press_kit_zip',
            field=models.ForeignKey(blank=True, help_text='Archivio compresso con tutti i materiali stampa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Press Kit completo (ZIP/RAR)'),
        ),
    ]
