# Generated by Django 5.2.11 on 2026-02-18 16:18

import django.db.models.deletion
import django_countries.fields
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtistListingPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Breve intro SEO per la pagina roster.",
                        verbose_name="Testo introduttivo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pagina Roster Artisti",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome genere"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Generato automaticamente dal nome.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Breve descrizione del genere (opzionale).",
                        verbose_name="Descrizione",
                    ),
                ),
            ],
            options={
                "verbose_name": "Genere musicale",
                "verbose_name_plural": "Generi musicali",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TargetEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Nome icona Lucide (es: 'party-popper', 'building-2').",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipologia evento",
                "verbose_name_plural": "Tipologie evento",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ArtistPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "artist_type",
                    models.CharField(
                        choices=[
                            ("show_band", "Show Band / Party Band"),
                            ("tribute", "Tribute Band"),
                            ("original", "Band Originale"),
                            ("dj", "DJ / Solista"),
                            ("cover", "Cover Band"),
                        ],
                        default="show_band",
                        max_length=20,
                        verbose_name="Tipologia artista",
                    ),
                ),
                (
                    "short_bio",
                    models.TextField(
                        help_text="Max 500 caratteri. Usata nelle card e snippet SEO.",
                        max_length=500,
                        verbose_name="Bio breve",
                    ),
                ),
                (
                    "hero_video_url",
                    models.URLField(
                        blank=True,
                        help_text="Se presente, l'header e' video-first (loop/preview).",
                        verbose_name="URL Video Hero (YouTube)",
                    ),
                ),
                (
                    "tribute_to",
                    models.CharField(
                        blank=True,
                        help_text="Nome artista/band tributato. Es: 'Queen', 'Vasco Rossi'. Migliora SEO.",
                        max_length=200,
                        verbose_name="Tributo a",
                    ),
                ),
                (
                    "base_country",
                    django_countries.fields.CountryField(
                        default="IT",
                        help_text="Paese operativo principale della band.",
                        max_length=2,
                        verbose_name="Paese base",
                    ),
                ),
                (
                    "base_region",
                    models.CharField(
                        blank=True,
                        help_text="Testo libero. Es: Piemonte, Lombardia, Bavaria.",
                        max_length=100,
                        verbose_name="Regione base",
                    ),
                ),
                (
                    "base_city",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Citta base"
                    ),
                ),
                ("spotify_url", models.URLField(blank=True, verbose_name="Spotify")),
                (
                    "instagram_url",
                    models.URLField(blank=True, verbose_name="Instagram"),
                ),
                ("facebook_url", models.URLField(blank=True, verbose_name="Facebook")),
                ("website_url", models.URLField(blank=True, verbose_name="Sito web")),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 2),
                            ("bio", 6),
                            ("discography", 14),
                            ("video", 18),
                            ("gallery", 26),
                            ("cta", 31),
                            ("richtext", 32),
                        ],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"max_length": 200}),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("h2", "H2"),
                                        ("h3", "H3"),
                                        ("h4", "H4"),
                                    ],
                                    "help_text": "Mai H1 — riservato al titolo pagina.",
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 0), ("level", 1)]],
                                {},
                            ),
                            3: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link", "ol", "ul"],
                                    "help_text": "Testo della biografia.",
                                },
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Citazione o frase di lancio dell'artista (opzionale).",
                                    "max_length": 300,
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Autore della citazione (opzionale).",
                                    "max_length": 100,
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("body", 3), ("quote", 4), ("quote_attribution", 5)]],
                                {},
                            ),
                            7: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "Discografia",
                                    "help_text": "Titolo della sezione.",
                                },
                            ),
                            8: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Titolo album.", "max_length": 200},
                            ),
                            9: (
                                "wagtail.blocks.IntegerBlock",
                                (),
                                {
                                    "help_text": "Anno di uscita.",
                                    "max_value": 2030,
                                    "min_value": 1950,
                                },
                            ),
                            10: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"help_text": "Copertina album.", "required": False},
                            ),
                            11: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "Link diretto Spotify dell'album.",
                                    "required": False,
                                },
                            ),
                            12: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 8),
                                        ("year", 9),
                                        ("cover_image", 10),
                                        ("spotify_url", 11),
                                    ]
                                ],
                                {},
                            ),
                            13: ("wagtail.blocks.ListBlock", (12,), {}),
                            14: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 7), ("albums", 13)]],
                                {},
                            ),
                            15: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {
                                    "help_text": "URL YouTube o Vimeo. Es: https://www.youtube.com/watch?v=..."
                                },
                            ),
                            16: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Didascalia sotto il video.",
                                    "max_length": 300,
                                    "required": False,
                                },
                            ),
                            17: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("normal", "Normale"),
                                        ("featured", "In evidenza (larghezza piena)"),
                                    ]
                                },
                            ),
                            18: (
                                "wagtail.blocks.StructBlock",
                                [[("video", 15), ("caption", 16), ("is_featured", 17)]],
                                {},
                            ),
                            19: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Gallery", "required": False},
                            ),
                            20: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("grid", "Griglia (3 colonne)"),
                                        ("carousel", "Carosello"),
                                        ("masonry", "Masonry"),
                                    ]
                                },
                            ),
                            21: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            22: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 200, "required": False},
                            ),
                            23: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Crediti fotografo.",
                                    "max_length": 100,
                                    "required": False,
                                },
                            ),
                            24: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 21), ("caption", 22), ("credit", 23)]],
                                {},
                            ),
                            25: ("wagtail.blocks.ListBlock", (24,), {}),
                            26: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 19), ("layout", 20), ("images", 25)]],
                                {},
                            ),
                            27: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Testo del bottone.", "max_length": 100},
                            ),
                            28: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"help_text": "Link esterno.", "required": False},
                            ),
                            29: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "help_text": "Oppure link a pagina interna.",
                                    "required": False,
                                },
                            ),
                            30: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("primary", "Primario (pieno)"),
                                        ("secondary", "Secondario (outline)"),
                                        ("accent", "Accent (gradient)"),
                                    ]
                                },
                            ),
                            31: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("text", 27),
                                        ("url", 28),
                                        ("page", 29),
                                        ("style", 30),
                                    ]
                                ],
                                {},
                            ),
                            32: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "bold",
                                        "italic",
                                        "link",
                                        "ol",
                                        "ul",
                                        "h3",
                                        "h4",
                                    ],
                                    "template": "core/blocks/richtext_block.html",
                                },
                            ),
                        },
                        verbose_name="Contenuto pagina",
                    ),
                ),
                (
                    "main_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Immagine principale",
                    ),
                ),
                (
                    "managing_group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Gruppo Wagtail i cui membri possono modificare questa band e i relativi eventi. Lasciare vuoto per accesso solo staff.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="auth.group",
                        verbose_name="Gruppo editor autorizzati",
                    ),
                ),
                (
                    "genres",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, to="artists.genre", verbose_name="Generi musicali"
                    ),
                ),
                (
                    "target_events",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True,
                        help_text="Per quali tipi di evento e' adatta questa band?",
                        to="artists.targetevent",
                        verbose_name="Tipologie evento target",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pagina Artista",
                "verbose_name_plural": "Pagine Artista",
            },
            bases=("wagtailcore.page",),
        ),
    ]
