# Generated by Django 5.2.11 on 2026-02-18 16:18

import django.db.models.deletion
import django_countries.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("artists", "0001_initial"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventListingPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(
                        blank=True, verbose_name="Testo introduttivo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pagina Calendario Eventi",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="Promoter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=200, verbose_name="Ragione sociale"),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Referente"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Telefono"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Visibili solo agli admin.",
                        verbose_name="Note interne",
                    ),
                ),
            ],
            options={
                "verbose_name": "Promoter",
                "verbose_name_plural": "Promoters",
                "ordering": ["company_name"],
            },
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nome venue")),
                ("city", models.CharField(max_length=100, verbose_name="Citta")),
                (
                    "province",
                    models.CharField(
                        blank=True,
                        help_text="Es: AL, MI, TO oppure Bayern, Ile-de-France",
                        max_length=10,
                        verbose_name="Provincia / Stato",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        help_text="Testo libero. Es: Piemonte, Lombardia, Bavaria, Catalonia",
                        max_length=100,
                        verbose_name="Regione",
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        default="IT",
                        help_text="Codice ISO 3166-1 alpha-2",
                        max_length=2,
                        verbose_name="Paese",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Indirizzo completo"
                    ),
                ),
                (
                    "zip_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="CAP / Codice postale"
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Capienza"
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Sito web")),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitudine",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitudine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venue",
                "verbose_name_plural": "Venues",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EventPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("start_date", models.DateField(null=True, verbose_name="Data inizio")),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Compilare solo per eventi multi-giorno.",
                        null=True,
                        verbose_name="Data fine",
                    ),
                ),
                (
                    "doors_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Apertura porte"
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(blank=True, null=True, verbose_name="Inizio show"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confermato"),
                            ("tentative", "Da confermare"),
                            ("cancelled", "Annullato"),
                            ("postponed", "Posticipato"),
                            ("sold_out", "Sold Out"),
                        ],
                        default="confirmed",
                        max_length=20,
                        verbose_name="Stato evento",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Pubblico"),
                            ("private", "Privato (non visibile nel calendario)"),
                        ],
                        default="public",
                        max_length=20,
                        verbose_name="Visibilita",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="Impostato automaticamente dal job notturno per eventi passati.",
                        verbose_name="Archiviato",
                    ),
                ),
                (
                    "description",
                    wagtail.fields.RichTextField(
                        blank=True, verbose_name="Descrizione evento"
                    ),
                ),
                (
                    "ticket_url",
                    models.URLField(blank=True, verbose_name="Link biglietti"),
                ),
                (
                    "ticket_price",
                    models.CharField(
                        blank=True,
                        help_text="Es: '15 + d.p.' oppure 'Ingresso libero'",
                        max_length=100,
                        verbose_name="Prezzo biglietti",
                    ),
                ),
                (
                    "featured_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Immagine evento",
                    ),
                ),
                (
                    "related_artist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="artists.artistpage",
                        verbose_name="Artista",
                    ),
                ),
                (
                    "promoter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="events.promoter",
                        verbose_name="Promoter",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="events.venue",
                        verbose_name="Venue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pagina Evento",
                "verbose_name_plural": "Pagine Evento",
                "ordering": ["-start_date"],
            },
            bases=("wagtailcore.page",),
        ),
    ]
