# Generated by Django 5.2.11 on 2026-02-18 16:18

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NavigationMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Nome interno, non visibile al pubblico. Es: 'Header Menu IT'",
                        max_length=100,
                        verbose_name="Nome menu",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("header", "Header (Navigazione principale)"),
                            ("footer_main", "Footer — Colonna principale"),
                            ("footer_legal", "Footer — Link legali"),
                            ("footer_social", "Footer — Social"),
                            ("mobile", "Mobile menu"),
                        ],
                        max_length=30,
                        verbose_name="Posizione",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("it", "Italiano"), ("en", "English")],
                        default="it",
                        max_length=5,
                        verbose_name="Lingua",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu navigazione",
                "verbose_name_plural": "Menu navigazione",
                "unique_together": {("location", "language")},
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "title_override",
                    models.CharField(
                        blank=True,
                        help_text="Se vuoto, usa il titolo della pagina linkata.",
                        max_length=100,
                        verbose_name="Titolo custom",
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        help_text="Usato solo se 'Pagina interna' e' vuoto.",
                        verbose_name="URL esterno",
                    ),
                ),
                (
                    "open_in_new_tab",
                    models.BooleanField(
                        default=False, verbose_name="Apri in nuova scheda"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Nome icona Lucide React (es: 'music', 'calendar', 'mail').",
                        max_length=50,
                        verbose_name="Icona",
                    ),
                ),
                (
                    "page_link",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                        verbose_name="Pagina interna",
                    ),
                ),
                (
                    "menu",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="navigation.navigationmenu",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
    ]
